# Need to generate your keys first and/or potentially customize the source of the pub key below
#
---
- name: Keys
  hosts: ocp-all:glusterfs
  gather_facts: no
  # strategy: free -- allows plays to execute regardless of how fast each node completes, since this playbook isn't node-interdependent.
  strategy: free
  tasks:
    - name: Distribute Keys
      authorized_key:
        user: root
        key: "{{ lookup('file','~/.ssh/id_rsa.pub') }}"
